version: '2'
services:
  tensorflow-gpu:
    build: .
    container_name: tensorflow-gpu
    restart: always
    tty: true
    volumes:
      - ./src:/root/src:ro
    working_dir: '/root'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
